/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import{generateWAMessageFromContent}from"@adiwajshing/baileys";import db from"../lib/database.js";let handler=async(n,{conn:t,participants:e,groupMetadata:a,isBotAdmin:i})=>{const{isBanned:o,welcome:s,detect:r,antiLink:c,antiLink2:d,delete:A,estranjerosnot:_,antifake1:l,antifake2:m,antiTraba:v,simi:p,soloAdmins:I}=db.data.chats[n.chat],{restrict:$,antiPrivado:g,nkNspm:h}=db.data.settings[t.user.jid],u=t.user.id.split(":")[0]+"@s.whatsapp.net",b="@"+t.user.id.split(":")[0],D=(String.fromCharCode(8206).repeat(850),`\n*Grupo* : _[ ${a.subject} ]_\n\n*Grupo baneado* : _${o?"[✓]":"[X]"}_\n\n*Bot participante* : ${NombreDelBot}\n_${b}_\n\n*Bot Admin?* : _${i?"[✓]":"[X]"}_\n\n*Bot* : _${opts.self?"MODO-PRIVADO [ ! ]":"MODO-PUBLICO [✓]"}_\n\n*Modo Restringido* : _${$?"ACTIVADO [✓]":"DESACTIVADO [X]"}_\n\n*Modo Solo-Admins* : _${I?"ACTIVADO [✓]":"DESACTIVADO [X]"}_\n\n*Anti-Privado* : _${g?"ACTIVADO [✓]":"DESACTIVADO [X]"}_\n\n*Ser Sub-Bot* : _${h?"ACTIVADO [✓]":"DESACTIVADO [X]"}_\n\n*Bienvenida* : _${s?"Activo [✓]":"Inactivo [X]"}_\n\n*Antilink* : _${c?"Activo [✓]":"Inactivo [X]"}_\n\n*Antilink 2* : _${d?"Activo [✓]":"Inactivo [X]"}_\n\n*Anti Extranjeros* : _${_?"Activo [✓]":"Inactivo [X]"}_\n\n*No Falsos* : _${l?"Activo [✓]":"Inactivo [X]"}_\n\n*No Falsos 2* : _${m?"Activo [✓]":"Inactivo [X]"}_\n\n*Detección* : _${r?"Activo [✓]":"Inactivo [X]"}_\n\n*Anti Eliminar* : _${A?"Inactivo [X]":"Activo [✓]"}_\n\n*Antitraba* : _${v?"Activo [✓]":"Inactivo [X]"}_\n\n*Chat Bot* : _${p?"Activo [✓]":"Inactivo [X]"}_\n`);try{const e=generateWAMessageFromContent(n.chat,{liveLocationMessage:{degreesLatitude:-4.4764769,degreesLongitude:142.4871568,caption:D,sequenceNumber:0x5e2b9e7ffcf11,timeOffset:8600,jpegThumbnail:null,contextInfo:{mentionedJid:[u]}}},{quoted:n});await t.relayMessage(n.chat,e.message,{messageId:e.key.id}),reacMoji(n.chat,t,"🪀",n)}catch(t){n.reply(D)}};handler.help=["estadobot"],handler.tags=["casual"],handler.command=/^estadobot$/i,handler.group=!0;export default handler;

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/