/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import{unlinkSync,readFileSync}from"fs";import{join}from"path";import{exec}from"child_process";import fs from"fs";let handler=async(e,{conn:t,args:o,__dirname:a,command:r})=>{const i=["https://youtube.com/channel/UC_Pp8pT9vbT15k5_-i6oseA?sub_confirmation=1","https://vm.tiktok.com/ZMLjP4RBS/","https://fb.watch/b7LOc9_LU2/","https://youtube.com/channel/UC_Pp8pT9vbT15k5_-i6oseA"];try{const n=e.quoted?e.quoted:e,l=(e.quoted?e.quoted:e.msg).mimetype||"";let s;if(/robot/.test(r)&&(s=["-filter_complex \"afftfilt=real='hypot(re,im)*sin(0)':imag='hypot(re,im)*cos(0)':win_size=512:overlap=0.75\""]),/aumentarbajo/.test(r)&&(s=["-af equalizer=f=34:width_type=o:width=2:g=25"]),/memedist/.test(r)&&(s=["-filter_complex vibrato=f=5"]),/inframundo/.test(r)&&(s=["-filter:a atempo=1.7,asetrate=3486"]),/nightcore/.test(r)&&(s=["-filter:a atempo=1.06,asetrate=44100*1.25"]),/ardilla/.test(r)&&(s=["-filter:a atempo=0.8,asetrate=68100"]),/superveloz/.test(r)&&(s=["-filter:a atempo=2.0,asetrate=55100"]),/demonio/.test(r)&&(s=["-filter:a atempo=1.6,asetrate=22100"]),/lento/.test(r)&&(s=["-filter:a atempo=0.6,asetrate=44100"]),/cursed/.test(r)&&(s=["-filter_complex acrusher=level_in=8:level_out=18:bits=8:mode=log:aa=1"]),/reversa/.test(r)&&(s=["-filter_complex areverse"]),/ventilador/.test(r)&&(s=["-filter_complex apulsator=mode=sine:hz=3:width=0.1:offset_r=0"]),!/audio/.test(l))return e.reply(`Envie ó Responda un audio/nota de voz, con el comando \n\n${Prefijo+r}\n`);{const l=getRandom(".mp3"),m=join(a,"../tmp/"+l),d=await n.download(!0);exec(`ffmpeg -i ${d} ${s[0]} ${m}`,(async(a,n,l)=>{if(await unlinkSync(d),a)return e.reply(MultiNK.Error1());const s=await readFileSync(m);await t.sendMessage(e.chat,{audio:s,contextInfo:{externalAdReply:{title:`🎧 ${NombreDelBot} 🎛️`,body:`${r}`,previewType:"PHOTO",thumbnail:fs.readFileSync("./multimedia/imagenes/logo.jpg"),sourceUrl:i[Math.floor(Math.random()*i.length)]}},mimetype:"audio/mp4",fileName:`${o[0]||r}.mp3`,ptt:!0},{quoted:e})})),reacMoji(e.chat,t,"⚙️",e)}}catch(e){throw e}};handler.help=["robot","aumentarbajo","memedist","inframundo","nightcore","ardilla","superveloz","demonio","lento","cursed","reversa","ventilador"],handler.tags=["conversor"],handler.command=/^(robot|aumentarbajo|memedist|inframundo|nightcore|ardilla|superveloz|demonio|lento|cursed|reversa|ventilador)$/i;export default handler;

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/