/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import gtts from"node-gtts";import{readFileSync,unlinkSync}from"fs";import{join}from"path";const defaultLang=MultiNK.Lengua();let handler=async(n,{conn:e,args:a,command:o,text:t})=>{if(t.length>600)return n.reply("Maximo de caracteres 600");let i,r=a[0],l=a.slice(1).join(" ");if(2!==(a[0]||"").length&&(r=defaultLang,l=a.join(" ")),!l&&n.quoted?.text&&(l=n.quoted.text),!l)return e.sendButton(n.chat,`*[ ! ] Por favor, despues de usar el comando ${o}, tiene que agregarle el prefijo del idioma en el cual desea escuchar el audio* \n`,`Ejemplo de uso:\n\n${Prefijo+o} es hola\n\n-> "es" = prefijo español\n--\x3e "hola" = texto\n`,NombreDelBot,[`*[ idiomas disponibles ]* :${String.fromCharCode(8206).repeat(850)}\n\`\`\`\n  'af': 'Africano',\n  'sq': 'Albanes',\n  'ar': 'Arabico',\n  'hy': 'Armenio',\n  'ca': 'Catalan',\n  'zh': 'Chino',\n  'zh-cn': 'Chino (Mandarin/China)',\n  'zh-tw': 'Chino (Mandarin/Taiwanes)',\n  'zh-yue': 'Chino (Cantones)',\n  'hr': 'Croata',\n  'cs': 'Checo',\n  'da': 'Danes',\n  'nl': 'Holandes',\n  'en': 'Ingles',\n  'en-au': 'Ingles (Australia)',\n  'en-uk': 'Ingles (Reino unido)',\n  'en-us': 'Ingles (Estados unidos)',\n  'eo': 'Esperanto',\n  'fi': 'Finlandes',\n  'fr': 'Frances',\n  'de': 'Aleman',\n  'el': 'Griego',\n  'ht': 'Criollo haitiano',\n  'hi': 'Hindio',\n  'hu': 'Hungaro',\n  'is': 'islandes',\n  'id': 'Indonesio',\n  'it': 'Italiano',\n  'ja': 'Japones',\n  'ko': 'Koreano',\n  'la': 'Latino',\n  'lv': 'Leton',\n  'mk': 'Macedonio',\n  'no': 'Noruego',\n  'pl': 'Polaco',\n  'pt': 'Portugues',\n  'pt-br': 'Portugues (Brazil)',\n  'ro': 'Rumano',\n  'ru': 'Ruso',\n  'sr': 'Serbio',\n  'sk': 'Slovaco',\n  'es': 'Español',\n  'es-es': 'Español (España)',\n  'es-us': 'Español (Estados Unidos)',\n  'sw': 'Swahili',\n  'sv': 'Sueco',\n  'ta': 'Tamil',\n  'th': 'Tailandes',\n  'tr': 'Turco',\n  'vi': 'Vietnamita',\n  'cy': 'Gales'\n\`\`\``,"</bromita>"],n);try{i=await tts(l,r)}catch(e){n.reply(MultiNK.Error0()),l=a.join(" "),i=await tts(l,defaultLang)}finally{i&&e.sendFile(n.chat,i,"audiotxt.opus",null,n,!0)}};handler.help=["voz <lenguaje> <texto>"],handler.tags=["herramienta"],handler.command=/^(voz|gtts|tts|vos)$/i,handler.limit=!0;export default handler;function tts(n,e=defaultLang){return new Promise(((a,o)=>{try{let o=gtts(e),t=join(global.__dirname(import.meta.url),"../tmp",1*new Date+".wav");o.save(t,n,(()=>{a(readFileSync(t)),unlinkSync(t)}))}catch(n){o(n)}}))}

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/