/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import fs from"fs";import{generateWAMessageFromContent}from"@adiwajshing/baileys";let handler=async(e,{conn:t,text:a,participants:o})=>{const n=o.map((e=>t.decodeJid(e.id))),i=e.quoted?e.quoted:e,d=(i.msg||i).mimetype||"",s=/image|video|sticker|audio/.test(d),m=["https://youtube.com/channel/UC_Pp8pT9vbT15k5_-i6oseA?sub_confirmation=1","https://vm.tiktok.com/ZMLjP4RBS/","https://fb.watch/b7LOc9_LU2/","https://youtube.com/channel/UC_Pp8pT9vbT15k5_-i6oseA"],l=String.fromCharCode(8206).repeat(850),r=`${a||"ˢᵉˣʸ ᴱˡ ᑫᵘᵉ ᴸᵒ ᴸᵉᵃ ⁷ʷ⁷"}`;if(s&&"imageMessage"===i.mtype&&r){const a=await(i.download?.());t.sendMessage(e.chat,{image:a,caption:r,contextInfo:{mentionedJid:n,externalAdReply:{thumbnail:fs.readFileSync("./multimedia/imagenes/logo.jpg"),sourceUrl:m[Math.floor(Math.random()*m.length)]}}},{quoted:e})}else if(s&&"videoMessage"===i.mtype&&r){const a=await(i.download?.());t.sendMessage(e.chat,{video:a,mentions:n,mimetype:"video/mp4",caption:r})}else if(s&&"audioMessage"===i.mtype&&r){const a=await(i.download?.());t.sendMessage(e.chat,{audio:a,contextInfo:{mentionedJid:n,externalAdReply:{body:r,thumbnail:fs.readFileSync("./multimedia/imagenes/logo.jpg"),sourceUrl:m[Math.floor(Math.random()*m.length)]}},mimetype:"audio/mp4",fileName:"Hidetag.mp3"})}else if(s&&"stickerMessage"===i.mtype&&r){const a=await(i.download?.());t.sendMessage(e.chat,{sticker:a,contextInfo:{mentionedJid:n,externalAdReply:{body:r,thumbnail:fs.readFileSync("./multimedia/imagenes/logo.jpg"),sourceUrl:m[Math.floor(Math.random()*m.length)]}}})}else await t.relayMessage(e.chat,{extendedTextMessage:{text:`${l}\n${r}\n`,contextInfo:{mentionedJid:n,externalAdReply:{thumbnail:fs.readFileSync("./multimedia/imagenes/logo.jpg"),sourceUrl:m[Math.floor(Math.random()*m.length)]}}}},{})};handler.help=["hidetag [mensaje]"],handler.tags=["grupos","admins"],handler.command=/^(totag|hidetag)$/i,handler.group=!0,handler.admin=!0;export default handler;

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/