/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import moment from"moment-timezone";let handler=async(m,{conn:a})=>{const t=moment().tz("America/Lima").format("DD/MM HH:mm"),e=moment().tz("America/Mexico_City").format("DD/MM HH:mm"),o=moment().tz("America/La_Paz").format("DD/MM HH:mm"),n=moment().tz("America/Santiago").format("DD/MM HH:mm"),r=moment().tz("America/Argentina/Buenos_Aires").format("DD/MM HH:mm"),i=moment().tz("America/Bogota").format("DD/MM HH:mm"),M=moment().tz("America/Guayaquil").format("DD/MM HH:mm"),H=moment().tz("America/Costa_Rica").format("DD/MM HH:mm"),D=moment().tz("America/Havana").format("DD/MM HH:mm"),c=moment().tz("America/Guatemala").format("DD/MM HH:mm"),A=moment().tz("America/Tegucigalpa").format("DD/MM HH:mm"),l=moment().tz("America/Managua").format("DD/MM HH:mm"),f=moment().tz("America/Panama").format("DD/MM HH:mm"),s=moment().tz("America/Montevideo").format("DD/MM HH:mm"),z=moment().tz("America/Caracas").format("DD/MM HH:mm"),$=moment().tz("America/Asuncion").format("DD/MM HH:mm"),u=moment().tz("America/New_York").format("DD/MM HH:mm"),d=moment().tz("Asia/Jakarta").format("DD/MM HH:mm"),g=moment().tz("America/Sao_Paulo").format("DD/MM HH:mm"),h=moment().tz("Africa/Malabo").format("DD/MM HH:mm");await a.sendMessage(m.chat,{text:`\`\`\`\n「 ZONA-HORARIA 🌎 」\n\n⌚Peru       : ${t}\n⌚Mexico     : ${e}\n⌚Bolivia    : ${o}\n⌚Chile      : ${n}\n⌚Argentina  : ${r}\n⌚Colombia   : ${i}\n⌚Ecuador    : ${M}\n⌚Costa_Rica : ${H}\n⌚Cuba       : ${D}\n⌚Guatemala  : ${c}\n⌚Honduras   : ${A}\n⌚Nicaragua  : ${l}\n⌚Panama     : ${f}\n⌚Uruguay    : ${s}\n⌚Venezuela  : ${z}\n⌚Paraguay   : ${$}\n⌚New York   : ${u}\n⌚Asia       : ${d}\n⌚Brasil     : ${g}\n⌚G.N.Q      : ${h}\n\`\`\`\n${String.fromCharCode(8206).repeat(850)}\nZona horaria del servidor actual:\n[ ${Intl.DateTimeFormat().resolvedOptions().timeZone} ]\n${moment().tz(Intl.DateTimeFormat().resolvedOptions().timeZone).format("DD/MM/YY HH:mm:ss")}`},{quoted:m}),reacMoji(m.chat,a,"📆",m)};handler.help=["horario"],handler.tags=["casual"],handler.command=/^horario$/i;export default handler;

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/