/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import db from"../lib/database.js";import{promises}from"fs";import{join}from"path";import{xpRange}from"../lib/levelling.js";let handler=async(e,{conn:i,__dirname:t,command:n,isPrems:o})=>{const r=JSON.parse(await promises.readFile(join(t,"../package.json")).catch((e=>({}))))||{},a=Object.keys(db.data.users).length,s=Object.values(db.data.users).filter((e=>1==e.registered)).length,{exp:l,level:m,role:d}=db.data.users[e.sender],{min:c,xp:p,max:u}=xpRange(m,global.multiplier);let $=await i.getName(e.sender);const b=o?"Si":"No",f=o?"∞":db.data.users[e.sender].limit,j=[{title:"Menu-Simple 🌌",rows:[{title:"Funciones-básicas",description:"~ᴸᶦˢᵗᵃ ᵈᵉ ᶜᵒᵐᵃⁿᵈᵒˢ ˢᶦᵐᵖˡᵉˢ~",rowId:`${Prefijo}menusimple`}]},{title:"Menu-Internet 🌐",rows:[{title:"Random-Menu",description:"~ᴸᶦˢᵗᵃ ᵈᵉ ᶜᵒᵐᵃⁿᵈᵒˢ ᵛᵃʳᶦᵃᵈᵒˢ~",rowId:`${Prefijo}randmenu`}]},{title:"Menu-Artístico 🎨",rows:[{title:"Crear-Logos",description:"~ᶜᵒᵐᵃⁿᵈᵒˢ ᵖᵃʳᵃ ᶜʳᵉᵃʳ ˡᵒᵍᵒˢ ʸ ᵐᵃˢ~",rowId:`${Prefijo}logofabrica`}]},{title:"Menu-Otaku/Anime 🀄",rows:[{title:"Random-Anime",description:"~ᶜᵒᵐᵃⁿᵈᵒˢ ᵒᵗᵃᵏᵘ⁻ᵃⁿᶦᵐᵉ ᵛᵃʳᶦᵃᵈᵒ~",rowId:`${Prefijo}mianime`}]},{title:"Menu-Hentai/Anime 🥵",rows:[{title:"La-Biblia",description:"~ᶜᵒᵐᵃⁿᵈᵒˢ ʰᵉⁿᵗᵃᶦ⁻ᶜᵃʳᵗᵒᵒⁿ ⁺¹⁸~",rowId:`${Prefijo}labiblia`}]},{title:"Menu-Completo ♻️",rows:[{title:"Principal",description:"~ᴸᶦˢᵗᵃ ᶜᵒᵐᵖˡᵉᵗᵃ ᵈᵉ ᵗᵒᵈᵒˢ ˡᵒˢ ᶜᵒᵐᵃⁿᵈᵒˢ~",rowId:`${Prefijo}menucompleto`}]}];await i.sendMessage(e.chat,{text:`║❂ Cliente: ${$}\n║❂ Premium: ${b}\n║❂ Limite restante: ${f}\n║❂ Nivel: ${m} (${l} / ${p})\n║❂ Rol: ${d}\n║❂ XP: ${l}\n╚══════════`,footer:`┏⊱ ${NombreDelBot}\n┗━⊱ ${MultiNK.Habla()} ✓`,title:`╔I [ \`\`\`${r.name}\`\`\` ]\n║❂ Base de datos: ${s} a ${a}\n║❂ Tiempo activo: ${timeString(process.uptime())}\n║❂ Version del bot: ${r.version}\n║❂ Dueño del bot: ${r.author.name}\n║❂ Prefijo único: 「 ${Prefijo} 」\n`,buttonText:"Seleccione un menu ✓ ",sections:j},{quoted:e}),reacMoji(e.chat,i,"📃",e)};handler.help=["menu"],handler.command=/^(menu|comandos|menú|help)$/i;export default handler;

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/