/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import db from"../lib/database.js";const items={comprar:{limit:{exp:1999},elixir:{nkoins:1666},basura:{nkoins:5}},vender:{elixir:{nkoins:125},basura:{nkoins:2}}},usercc=global.UsLimitesCmd;let handler=async(e,{command:r,args:o})=>{const a=db.data.users[e.sender],t=a.limit,i=Object.fromEntries(Object.entries(items[r.toLowerCase()]).filter((([e])=>e&&e in a))),n=usercc<=t?usercc==t?"Tus límites estan completos":`Acabas de superar el limite predefinido de ${usercc} por usuario, que hacker eres :0`:`No puedes comprar mas de ${usercc} limit, tu límite actual es: ${t}`,s=`\nUsar formato *${Prefijo}${r} [artículo] [cantidad]*\nEjemplo de uso: \n\n${Prefijo}${r} elixir 10\n    \n📍Lista de artículos: \n${Object.keys(i).map((e=>{let o=Object.keys(i[e]).find((e=>e in a));return`*-${global.rpg.emoticon(e)}${e}* ${"comprar"==r?"Costo":"Valor"} ${i[e][o]} ${global.rpg.emoticon(o)}${o}`.trim()})).join("\n")}\n`.trim(),l=(o[0]||"").toLowerCase(),c=1*Math.floor(isNumber(o[1])?Math.min(Math.max(parseInt(o[1]),1),Number.MAX_SAFE_INTEGER):1);if(!i[l])return e.reply(s);if("comprar"==r.toLowerCase()){if("limit"==o[0]&&o[1]>usercc)return e.reply(n);if(t>=usercc)return e.reply(n);let r=Object.keys(i[l]).find((e=>e in a));return a[r]<i[l][r]*c?e.reply(`No tienes suficiente ${global.rpg.emoticon(r)}${r} para comprar *${c}* ${global.rpg.emoticon(l)}${l}. Necesitas *${i[l][r]*c-a[r]}* ${r} para poder comprar`):(a[r]-=i[l][r]*c,a[l]+=c,e.reply(`Tú compraste *${c}* ${global.rpg.emoticon(l)}${l} ✓`))}return a[l]<c?e.reply(`No tienes suficiente *${global.rpg.emoticon(l)}${l}* para vender, tu solo tienes ${a[l]} artículos`):(a[l]-=c,a.nkoins+=i[l].nkoins*c,e.reply(`Vendiste *${c}* ${global.rpg.emoticon(l)}${l} ✓`))};handler.help=["comprar [artículo] [cantidad]","vender <artículo> <cantidad>"],handler.tags=["games"],handler.command=/^(comprar|vender)$/i;export default handler;function isNumber(e){return e?"number"==typeof(e=parseInt(e))&&!isNaN(e):e}

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/