/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import{sticker}from"../lib/sticker.js";import uploadFile from"../lib/uploadFile.js";import uploadImage from"../lib/uploadImage.js";import{webp2png}from"../lib/webp2mp4.js";import moment from"moment-timezone";let handler=async(e,{conn:r,args:t,text:a,command:o,groupMetadata:i})=>{let[n,l]=a.split`|`;if(!n)return e.reply(`Agregue el nombre del paquete y nombre del autor, ejemplo: \n\n${Prefijo+o} paquete|autor\n`);if(!l)return e.reply(`Agregue el nombre del paquete y nombre del autor ó viceversa, ejemplo: \n\n${Prefijo+o} paquete|autor\n`);moment().tz(Intl.DateTimeFormat().resolvedOptions().timeZone).format("DD/MM/YY HH:mm:ss");const m=await r.getName(e.sender);let s=!1;try{let a=e.quoted?e.quoted:e,i=(a.msg||a).mimetype||a.mediaType||"";if(/webp|image|video/g.test(i)){if(/video/g.test(i)&&(a.msg||a).seconds>8)return e.reply("*[ ! ] Máxima duración de vídeo son 7 segundos!*");let t,p=await(a.download?.());if(!p)return e.reply(`*[ ! ] Por favor Envie o Responda un video o una imagen usando el comando ${Prefijo+o}*\n_NOTA : duracion de video 1 a 10 segundos máximo_ ✓`);e.reply(MultiNK.Proces(m));try{s=await sticker(p,!1,n,l),reacMoji(e.chat,r,"⚙️",e)}catch(e){console.error(e)}finally{s||(/webp/g.test(i)?t=await webp2png(p):/image/g.test(i)?t=await uploadImage(p):/video/g.test(i)&&(t=await uploadFile(p)),"string"!=typeof t&&(t=await uploadImage(p)),s=await sticker(!1,t,n,l))}}else if(t[0]){if(!isUrl(t[0]))return e.reply("[ ! ] Url inválido, prueba con otro ;3");s=await sticker(!1,t[0],n,l)}}catch(e){console.error(e),s||(s=e)}finally{if(!s)return e.reply("[ ! ] Error");r.sendFile(e.chat,s,"sticker.webp","",e)}};handler.help=["wm [multimedia/url]"],handler.tags=["conversor","herramienta"],handler.command=/^(wm|stickerwm|swm|stickergifwm|sgifwm)$/i,handler.limit=!0;export default handler;const isUrl=e=>e.match(new RegExp(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&/=]*)(jpe?g|gif|png)/,"gi"));

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/