/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import axios from"axios";import db from"../lib/database.js";import{createHash}from"crypto";let handler=async(e,{conn:a,isPrems:i,isAdmin:r})=>{const n=await a.profilePictureUrl(e.sender,"image").catch((e=>"./multimedia/imagenes/avatar_contact.png")),o=await a.getName(e.sender),d=db.data.users[e.sender],t=createHash("md5").update(e.sender).digest("hex"),s=t?`\n➢ Codigo de registro : ${t}`:"";axios.get(`https://latam-api.vercel.app/api/infonum?apikey=${MyApiKey}&q=${e.sender.split("@")[0]}`).then((t=>{a.sendMessage(e.chat,{image:{url:n},caption:`💻 <[ PERFIL DE USUARIO]> 🌐\n\n⚡ | INFO DE USUARIO |\n➢ Nombre : ${o} \n${i?"➢ Usuario premium : Si":"➢ Usuario premium : No"} ${d.name.includes(o)?"":`\n➢ Nombre registrado : ${d.name}`} ${d.age<0?"":`\n➢ Edad : ${d.age}`} ${d.regTime<0?"":`\n➢ Fecha de registro : ${formatDate(new Date(d.regTime).getTime())}`} ${d.registered?s:""} ${r?"\n➢ Es administrador : [✓]":"\n➢ Es administrador : [X]"} ${e.isGroup?"\n➢ Solicitud desde : Un Grupo":"\n➢ Solicitud desde : Chat privado"} ${String.fromCharCode(8206).repeat(850)} \n➢ Pais : ${t.data.pais} \n➢ Prefijo de pais : ${t.data.pais_prefijo} \n➢ Origen del número : ${t.data.ubicacion||"No encontrado u.u"}\n➢ Link de Número : wa.me/${e.sender.split("@")[0]} ${t.data.valido?"\n➢ Número valido : [✓]":"\n➢ Número valido : [X]"} ${t.data.linea_tipo?"\n➢ Dispositivo mobil : [✓]":"\n➢ Dispositivo mobil : [X]"} \n➢ Operadora : ${t.data.operadora} \n➢ Tipo de linea : ${t.data.linea_tipo} \n➢ Formato local : ${t.data.form_local} \n➢ Formato internacional : ${t.data.form_internacional} \n➢ Código de pais : ${t.data.pais_codigo}\n`},{quoted:e})}),(t=>{a.sendMessage(e.chat,{image:{url:n},caption:`💻 <[ PERFIL DE USUARIO]> 🌐\n\n⚡ | INFO DE USUARIO |\n➢ Nombre : ${o} \n${i?"➢ Usuario premium : Si":"➢ Usuario premium : No"} ${d.name.includes(o)?"":`\n➢ Nombre registrado : ${d.name}`} ${d.age<0?"":`\n➢ Edad : ${d.age}`} ${d.regTime<0?"":`\n➢ Fecha de registro : ${formatDate(new Date(d.regTime).getTime())}`} ${d.registered?s:""} ${r?"\n➢ Es administrador : [✓]":"\n➢ Es administrador : [X]"} ${e.isGroup?"\n➢ Solicitud desde : Un Grupo":"\n➢ Solicitud desde : Chat privado"} ${String.fromCharCode(8206).repeat(850)} \n➢ Link de Número : wa.me/${e.sender.split("@")[0]} \n`.trim()},{quoted:e})}))};handler.help=["miperfil"],handler.tags=["casual"],handler.command=/^miperfil$/i;export default handler;

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/