/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import e,{existsSync as r,watch as l}from"fs";import{join as i,resolve as t}from"path";import*as n from"os";import o from"syntax-error";import a from"./import.js";import s from"./helper.js";let __dirname=s.__dirname(import.meta),rootDirectory=s.__dirname(i(__dirname,"../")),pluginFolder=s.__dirname(i(__dirname,"../plugins")),pluginFilter=e=>/\.(mc)?js$/.test(e),watcher={},plugins={},pluginFolders=[];async function loadPluginFiles(r=r,n=n,o={recursiveRead:!1}){let u=t(r);if(u in watcher)return;pluginFolders.push(u);let p=await e.promises.readdir(r);await Promise.all(p.map(async r=>{let l=i(u,r),t=s.__filename(l,!0),p=formatFilename(l);try{let d=await e.promises.lstat(t);if(!d.isFile()){o.recursiveRead&&await loadPluginFiles(t,n,o);return}let g=s.__filename(l),m=n(g);if(!m)return;let c=await a(g);c&&(plugins[p]=c)}catch(f){o.logger?.error(f,`[ ! ] Error al solicitar ${p}`),delete plugins[p]}}));let d=l(u,reload.bind(null,{logger:o.logger,pluginFolder:r,pluginFilter:n}));return d.on("close",()=>deletePluginFolder(u,!0)),watcher[u]=d,plugins=sortedPlugins(plugins)}function deletePluginFolder(e,r=!1){let l=t(e);l in watcher&&(r||watcher[l].close(),delete watcher[l],pluginFolders.splice(pluginFolders.indexOf(l),1))}async function reload({logger:l,pluginFolder:t=t,pluginFilter:n=n},u,p){if(n(p)){let d=s.__filename(i(t,p),!0),g=formatFilename(d);if(g in plugins){if(!r(d))return l?.warn(`[ ! ] Se elimin\xf3 el plugin - '${g}'`),delete plugins[g];l?.info(`[ ! ] Plugin - '${g}' - actualizado correctamente`)}else l?.info(`[ ! ] Plugin nuevo - '${g}'`);let m=await e.promises.readFile(d),c=o(m,p,{sourceType:"module",allowAwaitOutsideFunction:!0});if(c)l?.error(c,`[ ! ] Error de sintaxis al cargar - '${g}' - `);else try{let f=await a(d);f&&(plugins[g]=f)}catch(F){l?.error(F,`[ ! ] Error se necesita el plugin - '${g}' - `),delete plugins[g]}finally{plugins=sortedPlugins(plugins)}}}function formatFilename(e){let r=i(rootDirectory,"./");"win32"===n.platform()&&(r=r.replace(/\\/g,"\\\\"));let l=RegExp(`^${r}`),t=e.replace(l,"");return t}function sortedPlugins(e){return Object.fromEntries(Object.entries(e).sort(([e],[r])=>e.localeCompare(r)))}export{pluginFolder,pluginFilter,plugins,watcher,pluginFolders,loadPluginFiles,deletePluginFolder,reload};

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/