/**
</> Original base BochilGaming 
</> Recode simple by @NeKosmic
**/

import{WAMessageStubType as e}from"@adiwajshing/baileys";import t from"awesome-phonenumber";import a from"chalk";import{watchFile as r}from"fs";import i from"./helper.js";import m from"./database.js";import l from"moment-timezone";let terminalImage=i.opts.img?(await import("terminal-image")).default:"",urlRegex=(await import("url-regex-safe")).default({strict:!1});export default async function(e,r={user:{}}){let o=await r.getName(e.sender),s=t("+"+e.sender.replace("@s.whatsapp.net","")).getNumber("international")+(o?" ~"+o:""),n=await r.getName(e.chat),g;try{i.opts.img&&(g=!!/sticker|image/gi.test(e.mtype)&&await terminalImage.buffer(await e.download()))}catch(p){console.error(p)}let d=(e.msg?e.msg.vcard?e.msg.vcard.length:e.msg.fileLength?e.msg.fileLength.low||e.msg.fileLength:e.msg.axolotlSenderKeyDistributionMessage?e.msg.axolotlSenderKeyDistributionMessage.length:e.text?e.text.length:0:e.text?e.text.length:0)||0;if(m.data.users[e.sender],t("+"+((r.user?.jid||r.user?.id)?.replace("@s.whatsapp.net","")||"")).getNumber("international"),console.log("\x1b[1;31m~\x1b[1;37m>",a.white("["),a.blue(e.isCommand?"EJECUTANDO":"MENSAJE"),a.white("]"),a.green("{"),a.rgb(255,131,0).underline(e.text||e.isCommand||e.mtype||"-"),a.yellow(d+["B",..."KMGTP"][Math.floor(Math.log(d)/Math.log(1e3))]||""),a.green("}"),a.blue(e.isCommand?"Por":"De"),a.cyan(o),"Chat",e.isGroup?a.bgGreen("grupo:"+n):a.bgRed("Privado:"+s),"Fecha",a.magenta(l().tz(Intl.DateTimeFormat().resolvedOptions().timeZone).format("DD/MM/YY HH:mm:ss")).trim()),g&&console.log(g.trimEnd()),"string"==typeof e.text&&e.text){let u=e.text.replace(/\u200e+/g,""),f=/(?<=(?:^|[\s\n])\S?)(?:([*_~])(.+?)\1|```((?:.||[\n\r])+?)```)(?=\S?(?:[\s\n]|$))/g,c=(e=4)=>(t,r,i,m)=>{let l={_:"italic","*":"bold","~":"strikethrough"};return i=i||m,!l[r]||e<1?i:a[l[r]](i.replace(f,c(e-1)))};if(u.length<4096&&(u=u.replace(urlRegex,(e,t,r)=>{let i=e.length+t;return 0===t||i===r.length||/^\s$/.test(r[i])&&/^\s$/.test(r[t-1])?a.blueBright(e):e})),u=u.replace(f,c(4)),e.mentionedJid)for(let h of e.mentionedJid)u=u.replace("@"+h.split`@`[0],a.blueBright("@"+await r.getName(h)))}if(e.messageStubParameters.length&&console.log(e.messageStubParameters.map(e=>{e=r.decodeJid(e);let i=r.getName(e);return a.gray(t("+"+e.replace("@s.whatsapp.net","")).getNumber("international")+(i?" ~"+i:""))}).join(", ")),/document/i.test(e.mtype))console.log(`📄 ${e.msg.fileName||e.msg.displayName||"Document"}`);else if(/ContactsArray/i.test(e.mtype))console.log(`👨‍👩‍👧‍👦  `);else if(/contact/i.test(e.mtype))console.log(`👨 ${e.msg.displayName||""}`);else if(/audio/i.test(e.mtype)){let b=e.msg.seconds;console.log(`${e.msg.ptt?"\uD83C\uDFA4 (PTT ":"\uD83C\uDFB5 ("}AUDIO) ${Math.floor(b/60).toString().padStart(2,0)}:${(b%60).toString().padStart(2,0)}`)}console.log()};let file=i.__filename(import.meta.url);r(file,()=>{console.log(a.cyan("\n["+file+"] Fue actualizado con exito!\n"))});

/**
[_>] https://github.com/NeKosmic/
[_>] https://gitlab.com/NeKosmic/
**/